### ISSUE TITLE
`make spec` returns "TypeError: must be str, not bytes"

### ISSUE THREAD

**Issue by KurtPfeifle** [jgm/CommonMark#353]
~~~
$ make spec

  python3 tools/makespec.py html > spec.html
  Error converting markdown version of spec:
  Traceback (most recent call last):
    File "tools/makespec.py", line 162, in <module>
      sys.stderr.write(err)
  TypeError: must be str, not bytes
  make: *** [spec.html] Error 1
~~~

My `python3` is this:

~~~
$ python3 --version

  Python 3.4.2
~~~
 
----

`make spec.pdf` also returns an error:

~~~
$ make spec.pdf

  ! Undefined control sequence.
  <argument> \VariableTok 
                          {document}\NormalTok {.}\AttributeTok {getElementByI...
  l.5265 ...innerHTML}\NormalTok{␣}\OperatorTok{=}
  
  pandoc: Error producing PDF from TeX source
  make: *** [spec.pdf] Error 43
~~~

My Pandoc is:

~~~
$ pandoc --version

  pandoc 1.15.0.6
  Compiled with texmath 0.8.2.2, highlighting-kate 0.6.
~~~

**Comment by KurtPfeifle** [comment]
After doing a `git pull`, I'm ***still*** getting an error, now slightly different:

~~~
$ make spec
  
  python3 tools/makespec.py html > spec.html
  Traceback (most recent call last):
    File "tools/makespec.py", line 169, in <module>
      err("Error converting markdown version of spec:\n")
  TypeError: 'bytes' object is not callable
  make: *** [spec.html] Error 1
~~~
